// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP0g-SSeuXgSa4crBmrCLWavwrksQSOQk',
    appId: '1:31796873395:web:c4a15d7285eb17dd6848c6',
    messagingSenderId: '31796873395',
    projectId: 'soarkidz-8ac85',
    authDomain: 'soarkidz-8ac85.firebaseapp.com',
    databaseURL: 'https://soarkidz-8ac85-default-rtdb.firebaseio.com',
    storageBucket: 'soarkidz-8ac85.appspot.com',
    measurementId: 'G-50NECGL8FT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZgw-3_H_sli2Z5PHDIvmF2arw39jx8kA',
    appId: '1:31796873395:android:028d7b40fa2b75d66848c6',
    messagingSenderId: '31796873395',
    projectId: 'soarkidz-8ac85',
    databaseURL: 'https://soarkidz-8ac85-default-rtdb.firebaseio.com',
    storageBucket: 'soarkidz-8ac85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmDlTjUWb-xYjOvRHl_knXQfffxNMKu-M',
    appId: '1:31796873395:ios:110bf20f5077ffd36848c6',
    messagingSenderId: '31796873395',
    projectId: 'soarkidz-8ac85',
    databaseURL: 'https://soarkidz-8ac85-default-rtdb.firebaseio.com',
    storageBucket: 'soarkidz-8ac85.appspot.com',
    androidClientId: '31796873395-bdvg4i9ag22o4fvua33qpi6eh39cb02v.apps.googleusercontent.com',
    iosClientId: '31796873395-cggm7mn55jk1p5k95q6ddkedv0op00ej.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterwebchat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmDlTjUWb-xYjOvRHl_knXQfffxNMKu-M',
    appId: '1:31796873395:ios:e6bdd340db8d40596848c6',
    messagingSenderId: '31796873395',
    projectId: 'soarkidz-8ac85',
    databaseURL: 'https://soarkidz-8ac85-default-rtdb.firebaseio.com',
    storageBucket: 'soarkidz-8ac85.appspot.com',
    androidClientId: '31796873395-bdvg4i9ag22o4fvua33qpi6eh39cb02v.apps.googleusercontent.com',
    iosClientId: '31796873395-32a3ored7694od5bgjcq4o2qnd5lddvc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterwebchat.RunnerTests',
  );
}
