// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcam765TvsXo0_5gIE-C56BhAWsCPWPAI',
    appId: '1:50124109960:web:14ff393f7b54cad7e5073d',
    messagingSenderId: '50124109960',
    projectId: 'ysmeta-dfin',
    authDomain: 'ysmeta-dfin.firebaseapp.com',
    databaseURL: 'https://ysmeta-dfin-default-rtdb.firebaseio.com',
    storageBucket: 'ysmeta-dfin.appspot.com',
    measurementId: 'G-WB0CEJMB6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADXNJOeGlILR-Eo0XyGiz_cCAzIZL7Hmg',
    appId: '1:50124109960:android:9d7616370397effee5073d',
    messagingSenderId: '50124109960',
    projectId: 'ysmeta-dfin',
    databaseURL: 'https://ysmeta-dfin-default-rtdb.firebaseio.com',
    storageBucket: 'ysmeta-dfin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5FNZFQ-G0ZbWBDn3DVpOW68l9LmnWix4',
    appId: '1:50124109960:ios:a819d680eec8be83e5073d',
    messagingSenderId: '50124109960',
    projectId: 'ysmeta-dfin',
    databaseURL: 'https://ysmeta-dfin-default-rtdb.firebaseio.com',
    storageBucket: 'ysmeta-dfin.appspot.com',
    iosBundleId: 'com.ysmeta.dfin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5FNZFQ-G0ZbWBDn3DVpOW68l9LmnWix4',
    appId: '1:50124109960:ios:a80f9d3f1d2fc691e5073d',
    messagingSenderId: '50124109960',
    projectId: 'ysmeta-dfin',
    databaseURL: 'https://ysmeta-dfin-default-rtdb.firebaseio.com',
    storageBucket: 'ysmeta-dfin.appspot.com',
    iosBundleId: 'com.ysmeta.dfin.RunnerTests',
  );
}
